### ISSUE TITLE
Ping a Pypy developer here to help us improve this recipe

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/pypy3.6-feedstock#2]
Hi @mattip I would love to hear your thoughts on this recipe. I can walk you through it later today.

**Comment by mattip** [comment]
Couple of thoughts:
- are you using pypy2 to build on linux?
- you are using v7.1.0, we have released v7.1.1
- can we add a win32 path (PyPy does not support a 64-bit build on Windows)?

**Comment by ocefpaf** [comment]
This feedstock team is @omerbenamram and @ohadravid and they probably can answer it better but here is what I found out:

> are you using pypy2 to build on linux?

Based [on this line](https://github.com/conda-forge/pypy3.6-feedstock/blob/master/recipe/build.sh#L11) I think so.

> you are using v7.1.0, we have released v7.1.1

We are actually `7.1.0b` :scream:! Let's try to send a PR to update that during the sprints.

> can we add a win32 path (PyPy does not support a 64-bit build on Windows)?

conda-forge dropped support for `win32` a long time ago but we can probably make an exception for `pypy` if that is the only option.

**Comment by ohadravid** [comment]
Hi! Thanks for taking a look 😄 

>  are you using pypy2 to build on linux?

Only on macOS, because the old forge CI was timing-out. 
In theory we can switch to using regular python now.

> you are using v7.1.0, we have released v7.1.1

Ha, Missed that release 😳 

> can we add a win32 path (PyPy does not support a 64-bit build on Windows)?

We thought about it, but reading in the docs about building PyPy with the larger memory extensions seems a bit crazy to do in `conda-forge` CI.
In theory all the build tools should be there, so I don't think any special support from conda will be needed. 
Another reason for leaving out Windows is that it's less useful because the official `win32` release works for every Windows, unlike linux/macOS where we leverage conda's environment the ensure a working binary.
Another option is to use a precompiled binary, but the official one didn't work with the expected conda folder structure, but again I didn't gave this a lot of attention.

Note that we also have a [3.5 feedstock](https://github.com/conda-forge/pypy3.5-feedstock)  🙂

**Comment by mattip** [comment]
> are you using pypy2 to build on linux?

Building with pypy2 is significantly faster than building with cpython2. Rather than taking it out of darwin, it should be added to linux

The windows argument makes sense, thanks. I guess my misunderstanding is how windows users could leverage the directions to do `conda install -c conda-forge pypy3.6` to get pypy on windows.

**Comment by ohadravid** [comment]
The main reason I want to take it out is that it's kind of a lucky thing that the macOS slave used for the build works with the binary. For linux there's very little chance that could work.
Since we only build this once for every release of PyPy, I figured we handle the longer build for the reduced complexity. WDYT?

You are right that the directions will not work for Windows users, I'll add a clarification.

**Comment by mattip** [comment]
Discussing with @msarahan, we came to the conclusion (and I hope I am expressing it correctly), that we should add a version selector to `run_exports` that would be something like `pypy2.7.7.1` and `pypy3.6.7.1` (to mean pypy implementing python 2.7/3.6, version 7.1), and then `conda-build` would have to be taught to handle that.

Does this make sense?

**Comment by mattip** [comment]
Are there still open things here since #3 was merged?

**Comment by ohadravid** [comment]
I didn't really understand the `run_exports` part 😳 
Is there something we should do or should we wait for changes in `conda`?

But other than that I think we can close this for now.
@mattip / @ocefpaf ?

**Comment by ocefpaf** [comment]
> I didn't really understand the `run_exports` part

It should be something like this

```
  run_exports:
    - {{ pin_subpackage({{ name }}, max_pin='x.x.x') }}
```

In that case I'm "telling" dependencies built with this package to always run with the exactly same MAJOR.MINOR.MICRO version used to build them. If the ABI is stable to the MINOR or MAJOR version we can change that to `x.x` or `x`.

> Is there something we should do or should we wait for changes in `conda`?

You can try to add the `run_exports` but I believe we can proceed without it.

> But other than that I think we can close this for now.

Sure. No need to keep this open. It was just to introduce @mattip to the feedstock.
